function doAll() {
    firebase.auth().onAuthStateChanged(user => {
        if (user) {
            getBookmarks(user)
        } else {
            console.log("No user is signed in");
        }
    });
}
doAll();


function getBookmarks(user) {
    db.collection("users").doc(user.uid).get()
        .then(userDoc => {

					  // Get the Array of bookmarks
            var bookmarks = userDoc.data().bookmarks;
            console.log(bookmarks);
						
						// Get pointer the new card template
            let newcardTemplate = document.getElementById("historyCardTemplate");

						// Iterate through the ARRAY of bookmarked users (document ID's)
            bookmarks.forEach(thisUserID => {
                console.log(thisUserID);
                db.collection("users").doc(thisUserID).get().then(doc => {
                    var name = doc.data().name; // get value of the "name" key
                    // var hikeCode = doc.data().code; //get unique ID to each hike to be used for fetching right image
                    var department = doc.data().department; //gets the department field
                    var gender = doc.data().gender; //gets the department field
                    // var docID = doc.id;  //this is the autogenerated ID of the document
                    
                    //clone the new card
                    let newcard = newcardTemplate.content.cloneNode(true);

                    //update name and some pertinant information
                    newcard.querySelector('#buddy-name').innerHTML = name;
                    newcard.querySelector('#buddy-department').innerHTML = department;
                    newcard.querySelector('#buddy-gender').innerHTML = gender;
                    // newcard.querySelector('.card-image').src = `./images/${hikeCode}.jpg`; //Example: NV01.jpg
                    // newcard.querySelector('a').href = "eachHike.html?docID=" + docID;

                    //NEW LINE: update to display length, duration, last updated
                    // newcard.querySelector('.card-length').innerHTML =
                    //     "Length: " + doc.data().length + " km <br>" +
                    //     "Duration: " + doc.data().hike_time + "min <br>" +
                    //     "Last updated: " + doc.data().last_updated.toDate().toLocaleDateString();

										//Finally, attach this new card to the gallery
                    favouritesCardGroup.appendChild(newcard);
                })
            });
        })
}